{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "global-chart.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "global-chart.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secret }}
  {{- if kindIs "string" $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- else }}
  {{ $key }}: {{ toYaml $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
