apiVersion: v1
kind: Service
metadata:
  name: {{ include "global-chart.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "global-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: {{ .Values.service.portName | default "http" }}
  selector:
    {{- include "global-chart.selectorLabels" . | nindent 4 }}
