{{/*
Validation helpers for global-chart.
*/}}

{{/*
Validate that all generated resource names are unique after truncation.
Checks within each resource kind: Deployments, CronJobs, Jobs (hooks),
hook-prerequisite ConfigMaps, and hook-prerequisite Secrets.
Note: per-deployment resources (Service, SA, ConfigMap, Secret, HPA, PDB, NetworkPolicy)
share the same name as the Deployment itself and are covered by the deployment name check.
Called from validate.yaml.
*/}}
{{- define "global-chart.validateNameCollisions" -}}
{{- $root := . -}}
{{- $fullname := include "global-chart.fullname" $root -}}
{{- $deployNames := dict -}}
{{- $cronNames := dict -}}
{{- $hookNames := dict -}}
{{- $cmNames := dict -}}
{{- $secretNames := dict -}}

{{- /* 1. Deployment resource names (trunc 63) */ -}}
{{- range $name, $deploy := .Values.deployments -}}
  {{- if $deploy -}}
  {{- if eq (include "global-chart.deploymentEnabled" (dict "deploy" $deploy)) "true" -}}
    {{- $depFullname := include "global-chart.deploymentFullname" (dict "root" $root "deploymentName" $name) -}}
    {{- if hasKey $deployNames $depFullname -}}
      {{- fail (printf "Name collision: Deployment '%s' generated by deployment '%s' conflicts with %s" $depFullname $name (index $deployNames $depFullname)) -}}
    {{- end -}}
    {{- $_ := set $deployNames $depFullname (printf "deployment '%s'" $name) -}}

    {{- /* 1a. Deployment-level CronJob names (trunc 52) — matches cronjob.yaml naming */ -}}
    {{- range $jobName, $job := $deploy.cronJobs -}}
      {{- if $job -}}
        {{- $jobFullname := printf "%s-%s-%s" $fullname $name $jobName | trunc 52 | trimSuffix "-" -}}
        {{- if hasKey $cronNames $jobFullname -}}
          {{- fail (printf "Name collision: CronJob '%s' generated by cronJob '%s' in deployment '%s' conflicts with %s" $jobFullname $jobName $name (index $cronNames $jobFullname)) -}}
        {{- end -}}
        {{- $_ := set $cronNames $jobFullname (printf "cronJob '%s' in deployment '%s'" $jobName $name) -}}
      {{- end -}}
    {{- end -}}

    {{- /* 1b. Deployment-level Hook names (trunc 63) + prerequisite ConfigMap/Secret */ -}}
    {{- if $deploy.hooks -}}
      {{- /* Hook prerequisite ConfigMap (trunc 63) */ -}}
      {{- $hasDeployConfigMap := and $deploy.configMap (gt (len $deploy.configMap) 0) -}}
      {{- if $hasDeployConfigMap -}}
        {{- $hookConfigName := printf "%s-hook-config" $depFullname | trunc 63 | trimSuffix "-" -}}
        {{- if hasKey $cmNames $hookConfigName -}}
          {{- fail (printf "Name collision: ConfigMap '%s' generated by hook prerequisite for deployment '%s' conflicts with %s" $hookConfigName $name (index $cmNames $hookConfigName)) -}}
        {{- end -}}
        {{- $_ := set $cmNames $hookConfigName (printf "hook prerequisite ConfigMap for deployment '%s'" $name) -}}
      {{- end -}}

      {{- /* Hook prerequisite Secret (trunc 63) */ -}}
      {{- $hasDeploySecret := and $deploy.secret (gt (len $deploy.secret) 0) -}}
      {{- if $hasDeploySecret -}}
        {{- $hookSecretName := printf "%s-hook-secret" $depFullname | trunc 63 | trimSuffix "-" -}}
        {{- if hasKey $secretNames $hookSecretName -}}
          {{- fail (printf "Name collision: Secret '%s' generated by hook prerequisite for deployment '%s' conflicts with %s" $hookSecretName $name (index $secretNames $hookSecretName)) -}}
        {{- end -}}
        {{- $_ := set $secretNames $hookSecretName (printf "hook prerequisite Secret for deployment '%s'" $name) -}}
      {{- end -}}

      {{- range $hookType, $jobs := $deploy.hooks -}}
        {{- range $jobName, $command := $jobs -}}
          {{- if $command -}}
            {{- $hookFullname := printf "%s-%s-%s" $depFullname $hookType $jobName | trunc 63 | trimSuffix "-" -}}
            {{- if hasKey $hookNames $hookFullname -}}
              {{- fail (printf "Name collision: Job '%s' generated by hook '%s/%s' in deployment '%s' conflicts with %s" $hookFullname $hookType $jobName $name (index $hookNames $hookFullname)) -}}
            {{- end -}}
            {{- $_ := set $hookNames $hookFullname (printf "hook '%s/%s' in deployment '%s'" $hookType $jobName $name) -}}
          {{- end -}}
        {{- end -}}
      {{- end -}}
    {{- end -}}

  {{- end -}}
  {{- end -}}
{{- end -}}

{{- /* 2. Root-level CronJob names (trunc 52) */ -}}
{{- range $name, $job := .Values.cronJobs -}}
  {{- if $job -}}
    {{- $jobFullname := printf "%s-%s" $fullname $name | trunc 52 | trimSuffix "-" -}}
    {{- if hasKey $cronNames $jobFullname -}}
      {{- fail (printf "Name collision: CronJob '%s' generated by root cronJob '%s' conflicts with %s" $jobFullname $name (index $cronNames $jobFullname)) -}}
    {{- end -}}
    {{- $_ := set $cronNames $jobFullname (printf "root cronJob '%s'" $name) -}}
  {{- end -}}
{{- end -}}

{{- /* 3. Root-level Hook names (trunc 63) */ -}}
{{- range $hookType, $jobs := .Values.hooks -}}
  {{- range $name, $command := $jobs -}}
    {{- if $command -}}
      {{- $hookFullname := include "global-chart.hookfullname" (merge (dict "hookname" $hookType "jobname" $name) $root) -}}
      {{- if hasKey $hookNames $hookFullname -}}
        {{- fail (printf "Name collision: Job '%s' generated by root hook '%s/%s' conflicts with %s" $hookFullname $hookType $name (index $hookNames $hookFullname)) -}}
      {{- end -}}
      {{- $_ := set $hookNames $hookFullname (printf "root hook '%s/%s'" $hookType $name) -}}
    {{- end -}}
  {{- end -}}
{{- end -}}

{{- end }}
