{{/*
Validation helpers for global-chart.
*/}}

{{/*
Validate that all generated resource names are unique after truncation.
Checks within each resource kind: Deployments, CronJobs, Jobs (hooks),
hook-prerequisite ConfigMaps, and hook-prerequisite Secrets.
Note: per-deployment resources (Service, SA, ConfigMap, Secret, HPA, ScaledObject, PDB, NetworkPolicy)
share the same name as the Deployment itself and are covered by the deployment name check.
Called from validate.yaml.
*/}}
{{- define "global-chart.validateNameCollisions" -}}
{{- $root := . -}}
{{- $deployNames := dict -}}
{{- $cronNames := dict -}}
{{- $hookNames := dict -}}
{{- $cmNames := dict -}}
{{- $secretNames := dict -}}

{{- /* 1. Deployment resource names (trunc 63) */ -}}
{{- range $name, $deploy := .Values.deployments -}}
  {{- if $deploy -}}
  {{- if eq (include "global-chart.deploymentEnabled" (dict "deploy" $deploy)) "true" -}}
    {{- $depFullname := include "global-chart.deploymentFullname" (dict "root" $root "deploymentName" $name) -}}
    {{- if hasKey $deployNames $depFullname -}}
      {{- fail (printf "Name collision: Deployment '%s' generated by deployment '%s' conflicts with %s" $depFullname $name (index $deployNames $depFullname)) -}}
    {{- end -}}
    {{- $_ := set $deployNames $depFullname (printf "deployment '%s'" $name) -}}

    {{- /* 1a. Deployment-level CronJob names (trunc 52) — via deploymentCronJobName helper */ -}}
    {{- range $jobName, $job := $deploy.cronJobs -}}
      {{- if $job -}}
        {{- $jobFullname := include "global-chart.deploymentCronJobName" (dict "root" $root "deploymentName" $name "jobName" $jobName) -}}
        {{- if hasKey $cronNames $jobFullname -}}
          {{- fail (printf "Name collision: CronJob '%s' generated by cronJob '%s' in deployment '%s' conflicts with %s" $jobFullname $jobName $name (index $cronNames $jobFullname)) -}}
        {{- end -}}
        {{- $_ := set $cronNames $jobFullname (printf "cronJob '%s' in deployment '%s'" $jobName $name) -}}
      {{- end -}}
    {{- end -}}

    {{- /* 1b. Deployment-level Hook names (trunc 63) + prerequisite ConfigMap/Secret */ -}}
    {{- if $deploy.hooks -}}
      {{- /* Hook prerequisite ConfigMap (trunc 63) */ -}}
      {{- $hasDeployConfigMap := and $deploy.configMap (gt (len $deploy.configMap) 0) -}}
      {{- if $hasDeployConfigMap -}}
        {{- $hookConfigName := include "global-chart.hookPrereqConfigName" (dict "deploymentFullname" $depFullname) -}}
        {{- if hasKey $cmNames $hookConfigName -}}
          {{- fail (printf "Name collision: ConfigMap '%s' generated by hook prerequisite for deployment '%s' conflicts with %s" $hookConfigName $name (index $cmNames $hookConfigName)) -}}
        {{- end -}}
        {{- $_ := set $cmNames $hookConfigName (printf "hook prerequisite ConfigMap for deployment '%s'" $name) -}}
      {{- end -}}

      {{- /* Hook prerequisite Secret (trunc 63) */ -}}
      {{- $hasDeploySecret := and $deploy.secret (gt (len $deploy.secret) 0) -}}
      {{- if $hasDeploySecret -}}
        {{- $hookSecretName := include "global-chart.hookPrereqSecretName" (dict "deploymentFullname" $depFullname) -}}
        {{- if hasKey $secretNames $hookSecretName -}}
          {{- fail (printf "Name collision: Secret '%s' generated by hook prerequisite for deployment '%s' conflicts with %s" $hookSecretName $name (index $secretNames $hookSecretName)) -}}
        {{- end -}}
        {{- $_ := set $secretNames $hookSecretName (printf "hook prerequisite Secret for deployment '%s'" $name) -}}
      {{- end -}}

      {{- range $hookType, $jobs := $deploy.hooks -}}
        {{- range $jobName, $command := $jobs -}}
          {{- if $command -}}
            {{- /* Canonical 4-part single-trunc name via shared helper — keeps validator byte-identical to hook.yaml (prior depFullname-based double-trunc only diverged for K8s-invalid trailing-dash names) */ -}}
            {{- $hookFullname := include "global-chart.deploymentHookName" (dict "root" $root "deploymentName" $name "hookType" $hookType "jobName" $jobName) -}}
            {{- if hasKey $hookNames $hookFullname -}}
              {{- fail (printf "Name collision: Job '%s' generated by hook '%s/%s' in deployment '%s' conflicts with %s" $hookFullname $hookType $jobName $name (index $hookNames $hookFullname)) -}}
            {{- end -}}
            {{- $_ := set $hookNames $hookFullname (printf "hook '%s/%s' in deployment '%s'" $hookType $jobName $name) -}}
          {{- end -}}
        {{- end -}}
      {{- end -}}
    {{- end -}}

  {{- end -}}
  {{- end -}}
{{- end -}}

{{- /* 2. Root-level CronJob names (trunc 52) */ -}}
{{- range $name, $job := .Values.cronJobs -}}
  {{- if $job -}}
    {{- $jobFullname := include "global-chart.rootCronJobName" (dict "root" $root "name" $name) -}}
    {{- if hasKey $cronNames $jobFullname -}}
      {{- fail (printf "Name collision: CronJob '%s' generated by root cronJob '%s' conflicts with %s" $jobFullname $name (index $cronNames $jobFullname)) -}}
    {{- end -}}
    {{- $_ := set $cronNames $jobFullname (printf "root cronJob '%s'" $name) -}}
  {{- end -}}
{{- end -}}

{{- /* 3. Root-level Hook names (trunc 63) */ -}}
{{- range $hookType, $jobs := .Values.hooks -}}
  {{- range $name, $command := $jobs -}}
    {{- if $command -}}
      {{- $hookFullname := include "global-chart.hookfullname" (merge (dict "hookname" $hookType "jobname" $name) $root) -}}
      {{- if hasKey $hookNames $hookFullname -}}
        {{- fail (printf "Name collision: Job '%s' generated by root hook '%s/%s' conflicts with %s" $hookFullname $hookType $name (index $hookNames $hookFullname)) -}}
      {{- end -}}
      {{- $_ := set $hookNames $hookFullname (printf "root hook '%s/%s'" $hookType $name) -}}
    {{- end -}}
  {{- end -}}
{{- end -}}

{{- end }}

{{/*
Validate that .Values.ingress and .Values.httpRoute are not both enabled.
The chart supports only one routing layer per release; both being enabled
would render conflicting top-level routing resources.
Called from validate.yaml. Emits nothing on success.
*/}}
{{- define "global-chart.validateRoutingConflict" -}}
{{- $ing := default (dict) .Values.ingress -}}
{{- $rt := default (dict) .Values.httpRoute -}}
{{- $ingEnabled := default false $ing.enabled -}}
{{- $rtEnabled := default false $rt.enabled -}}
{{- if and $ingEnabled $rtEnabled -}}
{{- fail "Both .Values.ingress.enabled and .Values.httpRoute.enabled are true. The chart supports only one routing layer per release. Disable one (set enabled: false) to proceed." -}}
{{- end -}}
{{- end }}

{{/*
Validate that a deployment does not enable both the native HPA and KEDA.
KEDA creates and owns its own HorizontalPodAutoscaler (the *derived HPA*) for
every ScaledObject, so a chart-rendered HPA on the same Deployment gives two
controllers writing spec.replicas.
Called from validate.yaml. Emits nothing on success.
*/}}
{{- define "global-chart.validateAutoscalingConflict" -}}
{{- range $name, $deploy := .Values.deployments -}}
  {{- if $deploy -}}
  {{- if eq (include "global-chart.deploymentEnabled" (dict "deploy" $deploy)) "true" -}}
    {{- $hpa := default (dict) $deploy.autoscaling -}}
    {{- $keda := default (dict) $deploy.keda -}}
    {{- if and $hpa.enabled $keda.enabled -}}
      {{- fail (printf "deployments.%s: autoscaling.enabled and keda.enabled are mutually exclusive. KEDA creates and owns its own HorizontalPodAutoscaler for the ScaledObject; a chart-rendered HPA on the same Deployment would fight it. Disable one of the two." $name) -}}
    {{- end -}}
  {{- end -}}
  {{- end -}}
{{- end -}}
{{- end }}

{{/*
Validate that every named Service targetPort resolves to a container port the
chart declares.

A targetPort naming a port that no container declares is the one Service
misconfiguration Kubernetes accepts in silence: the Service is created, the pod
is Ready, and the port simply has no endpoints. It surfaces at request time, far
from its cause. Numbers need no check — a numeric targetPort reaches a pod port
whether or not the container declares it.
Called from validate.yaml. Emits nothing on success.
*/}}
{{- define "global-chart.validateServiceTargetPorts" -}}
{{- range $name, $deploy := .Values.deployments -}}
  {{- if $deploy -}}
  {{- if eq (include "global-chart.deploymentEnabled" (dict "deploy" $deploy)) "true" -}}
    {{- $svc := default (dict) $deploy.service -}}
    {{- if or (not (hasKey $svc "enabled")) $svc.enabled -}}
      {{- $declared := dict -}}
      {{- range (include "global-chart.containerPorts" $svc | fromJsonArray) -}}
        {{- $_ := set $declared .name true -}}
      {{- end -}}
      {{- $known := keys $declared | sortAlpha | join ", " -}}
      {{- $targetPort := include "global-chart.serviceTargetPort" $svc -}}
      {{- if and (hasKey $svc "targetPort") (kindIs "string" $svc.targetPort) (not (hasKey $declared $targetPort)) -}}
        {{- fail (printf "deployments.%s.service.targetPort names the port '%s', which no container port declares (declared: %s). A Service port whose targetPort names nothing gets no endpoints. Use the port number, or a name one of the declared ports carries." $name $targetPort $known) -}}
      {{- end -}}
      {{- range (default (list) $svc.extraPorts) -}}
        {{- if and (kindIs "string" .targetPort) (not (hasKey $declared .targetPort)) -}}
          {{- fail (printf "deployments.%s.service.extraPorts '%s' has targetPort '%s', which no container port declares (declared: %s). A Service port whose targetPort names nothing gets no endpoints. Give it the port number instead, and it will be declared on the container under this name." $name .name .targetPort $known) -}}
        {{- end -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
  {{- end -}}
{{- end -}}
{{- end }}
