{{- $root := . }}
{{- range $name, $deploy := .Values.deployments }}
{{- if $deploy }}
{{- if and (eq (include "global-chart.deploymentEnabled" (dict "deploy" $deploy)) "true") $deploy.configMap }}
{{- $depFullname := include "global-chart.deploymentFullname" (dict "root" $root "deploymentName" $name) }}
{{- $labelCtx := dict "root" $root "deploymentName" $name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $depFullname }}
  labels:
    {{- include "global-chart.deploymentLabels" $labelCtx | nindent 4 }}
  {{- with (include "global-chart.renderCommonAnnotations" $root) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  {{- include "global-chart.renderConfigMapData" $deploy.configMap | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
