{{- $root := . }}
{{- range $role := $root.Values.rbacs.roles }}
{{- $sa := $role.serviceAccount }}
{{- $saName := "" }}
{{- $saCreate := false }}
{{- if $sa }}
{{- $defaultSaName := printf "%s-sa" $role.name | trunc 63 | trimSuffix "-" }}
{{- $saName = ternary $sa.name $defaultSaName (hasKey $sa "name") }}
{{- $saCreate = true }}
{{- if hasKey $sa "create" }}
  {{- $saCreate = $sa.create }}
{{- end }}
{{- end }}
{{- if and $sa $saCreate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    {{- include "global-chart.labels" $root | nindent 4 }}
  {{- with (include "global-chart.renderAnnotations" (dict "root" $root "own" $sa.annotations)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ hasKey $sa "automount" | ternary $sa.automount true }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $role.name }}
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    {{- include "global-chart.labels" $root | nindent 4 }}
  {{- with (include "global-chart.renderAnnotations" (dict "root" $root)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
{{- with $role.rules }}
{{ toYaml . | indent 2 }}
{{- else }}
  []
{{- end }}
---
{{- if $saName }}
{{- $roleBindingName := printf "%s-rolebinding" (trimSuffix "-role" $role.name) | trunc 63 | trimSuffix "-" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $roleBindingName }}
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    {{- include "global-chart.labels" $root | nindent 4 }}
  {{- with (include "global-chart.renderAnnotations" (dict "root" $root)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $role.name }}
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ $root.Release.Namespace | quote }}
---
{{- end }}
{{- end }}
