{{- $root := . }}
{{- range $role := $root.Values.rbacs.roles }}
{{- $sa := default (dict) $role.serviceAccount }}
{{- $saInfo := include "global-chart.rbacServiceAccount" $role | fromJson }}
{{- $saName := default "" $saInfo.name }}
{{- if $saInfo.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    {{- include "global-chart.labels" $root | nindent 4 }}
  {{- with (include "global-chart.renderAnnotations" (dict "root" $root "own" $sa.annotations)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ hasKey $sa "automount" | ternary $sa.automount true }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $role.name }}
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    {{- include "global-chart.labels" $root | nindent 4 }}
  {{- with (include "global-chart.renderAnnotations" (dict "root" $root)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
{{- with $role.rules }}
{{ toYaml . | indent 2 }}
{{- else }}
  []
{{- end }}
---
{{- if $saName }}
{{- $roleBindingName := include "global-chart.rbacRoleBindingName" $role.name }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $roleBindingName }}
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    {{- include "global-chart.labels" $root | nindent 4 }}
  {{- with (include "global-chart.renderAnnotations" (dict "root" $root)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $role.name }}
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ $root.Release.Namespace | quote }}
---
{{- end }}
{{- end }}
