{{- $root := . }}
{{- range $name, $deploy := .Values.deployments }}
{{- if $deploy }}
{{- if eq (include "global-chart.deploymentEnabled" (dict "deploy" $deploy)) "true" }}
{{- $sa := default (dict) $deploy.serviceAccount }}
{{- $create := ternary $sa.create true (hasKey $sa "create") -}}{{/* Default to create=true unless explicitly set to false */}}
{{- if $create }}
{{- $depFullname := include "global-chart.deploymentFullname" (dict "root" $root "deploymentName" $name) }}
{{- $labelCtx := dict "root" $root "deploymentName" $name }}
{{- $saName := include "global-chart.deploymentServiceAccountName" (dict "root" $root "deploymentName" $name "deployment" $deploy) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    {{- include "global-chart.deploymentLabels" $labelCtx | nindent 4 }}
  {{- if or (include "global-chart.renderCommonAnnotations" $root) $sa.annotations }}
  annotations:
    {{- with (include "global-chart.renderCommonAnnotations" $root) }}
    {{- . | nindent 4 }}
    {{- end }}
    {{- with $sa.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ hasKey $sa "automount" | ternary $sa.automount true }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
