{{- $root := . }}
{{- range $name, $deploy := .Values.deployments }}
{{- if $deploy }}
{{- if eq (include "global-chart.deploymentEnabled" $deploy) "true" }}
{{- $sa := include "global-chart.deploymentServiceAccount" (dict "root" $root "deploymentName" $name "deployment" $deploy) | fromJson }}
{{- if $sa.create }}
{{- $labelCtx := dict "root" $root "deploymentName" $name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name }}
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    {{- include "global-chart.deploymentLabels" $labelCtx | nindent 4 }}
  {{- with (include "global-chart.renderAnnotations" (dict "root" $root "own" $sa.annotations)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $sa.automount }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
