{{- $root := . }}
{{- range $name, $deploy := .Values.deployments }}
{{- if $deploy }}
{{- if eq (include "global-chart.deploymentEnabled" (dict "deploy" $deploy)) "true" }}
{{- $svc := default (dict) $deploy.service }}
{{- $svcEnabled := true }}
{{- if and (hasKey $svc "enabled") (not $svc.enabled) }}
{{- $svcEnabled = false }}
{{- end }}
{{- if $svcEnabled }}
{{- $depFullname := include "global-chart.deploymentFullname" (dict "root" $root "deploymentName" $name) }}
{{- $labelCtx := dict "root" $root "deploymentName" $name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $depFullname }}
  labels:
    {{- include "global-chart.deploymentLabels" $labelCtx | nindent 4 }}
  {{- with (include "global-chart.renderCommonAnnotations" $root) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ ternary $svc.type "ClusterIP" (hasKey $svc "type") }}
  ports:
    - port: {{ ternary $svc.port 80 (hasKey $svc "port") }}
      targetPort: {{ ternary $svc.targetPort "http" (hasKey $svc "targetPort") }}
      protocol: {{ (ternary $svc.protocol "TCP" (hasKey $svc "protocol")) | upper }}
      name: {{ ternary $svc.portName "http" (hasKey $svc "portName") }}
  selector:
    {{- include "global-chart.deploymentSelectorLabels" $labelCtx | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
