name: Helm Chart Testing with KIND

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  helm-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        values_file:
          - tests/values.01.yaml
          - tests/values.02.yaml
          - tests/values.03.yaml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.x"
          check-latest: true

      - name: Install chart-testing tool
        uses: helm/chart-testing-action@v2.7.0

      - name: Create KIND cluster
        uses: helm/kind-action@v1.12.0

      - name: Lint Helm chart with ${{ matrix.values_file }}
        run: |
          echo "Linting chart in global-chart with values file: ${{ matrix.values_file }}"
          ct lint --chart-dirs global-chart --target-branch main --all -- --values ${{ matrix.values_file }}

      - name: Install Helm chart with ${{ matrix.values_file }}
        run: |
          echo "Installing chart in global-chart with values file: ${{ matrix.values_file }}"
          ct install --chart-dirs global-chart --target-branch main --all -- --values ${{ matrix.values_file }}
